CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    is_superuser BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stocks (
    symbol VARCHAR(32) PRIMARY KEY,
    name VARCHAR(255),
    ticker_id VARCHAR(64),
    ngx_id VARCHAR(64),
    sector VARCHAR(128),
    last_price NUMERIC(18, 4),
    previous_close NUMERIC(18, 4),
    open_price NUMERIC(18, 4),
    high_price NUMERIC(18, 4),
    low_price NUMERIC(18, 4),
    volume NUMERIC(20, 2),
    market_cap NUMERIC(24, 2),
    change NUMERIC(18, 4),
    percent_change NUMERIC(10, 4),
    margin NUMERIC(10, 4),
    source VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stock_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_symbol VARCHAR(32) NOT NULL REFERENCES stocks(symbol) ON DELETE CASCADE,
    trade_date DATE NOT NULL,
    open_price NUMERIC(18, 4),
    high_price NUMERIC(18, 4),
    low_price NUMERIC(18, 4),
    close_price NUMERIC(18, 4) NOT NULL,
    volume NUMERIC(20, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_stock_prices_symbol_date UNIQUE (stock_symbol, trade_date)
);

CREATE TABLE IF NOT EXISTS portfolio_holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    stock_symbol VARCHAR(32) NOT NULL REFERENCES stocks(symbol) ON DELETE RESTRICT,
    quantity NUMERIC(20, 4) NOT NULL,
    avg_purchase_price NUMERIC(18, 4) NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_portfolio_user_stock UNIQUE (user_id, stock_symbol)
);

CREATE TABLE IF NOT EXISTS sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    source VARCHAR(64) NOT NULL,
    stocks_upserted INTEGER NOT NULL DEFAULT 0,
    history_rows_upserted INTEGER NOT NULL DEFAULT 0,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS market_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(128) NOT NULL,
    source VARCHAR(64) NOT NULL DEFAULT 'ngx_doclib',
    message TEXT,
    raw_payload TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_stocks_ticker_id ON stocks(ticker_id);
CREATE INDEX IF NOT EXISTS ix_stocks_ngx_id ON stocks(ngx_id);
CREATE INDEX IF NOT EXISTS ix_stock_prices_symbol_date ON stock_prices(stock_symbol, trade_date);
CREATE INDEX IF NOT EXISTS ix_portfolio_holdings_user_id ON portfolio_holdings(user_id);
CREATE INDEX IF NOT EXISTS ix_sync_logs_status ON sync_logs(status);
CREATE INDEX IF NOT EXISTS ix_sync_logs_source ON sync_logs(source);
CREATE INDEX IF NOT EXISTS ix_market_status_status ON market_status(status);
