import asyncio
import logging
from contextlib import suppress
from datetime import date

from dateutil.relativedelta import relativedelta
from fastapi import Depends, FastAPI, HTTPException, Query, status
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import func, select, text
from sqlalchemy.orm import Session, selectinload

from .auth import create_access_token, get_current_superuser, get_current_user, hash_password, verify_password
from .database import Base, SessionLocal, engine, get_db
from .models import PortfolioHolding, Stock, User
from .schemas import (
    HoldingOut,
    HoldingUpsert,
    LoginRequest,
    RegisterRequest,
    StockOut,
    StockPriceOut,
    MarketStatusOut,
    SyncLogOut,
    SyncResult,
    SyncStatusOut,
    TokenResponse,
    UserOut,
)
from .services import (
    delete_holding,
    get_cached_market_status,
    holding_to_dict,
    record_sync_log,
    refresh_market_status,
    stock_history_query,
    sync_logs_query,
    sync_status,
    sync_stocks,
    upsert_holding,
    upsert_stock_history,
)
from .settings import get_settings


settings = get_settings()
logger = logging.getLogger("ngx_dash")
stock_sync_task: asyncio.Task | None = None
app = FastAPI(title=settings.app_name)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origin_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


async def background_stock_sync_loop() -> None:
    interval = max(1, settings.stock_sync_interval_seconds)
    while True:
        db = SessionLocal()
        try:
            await asyncio.to_thread(sync_stocks, db, False)
            await asyncio.to_thread(refresh_market_status, db)
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            logger.exception("Background stock sync failed")
            with suppress(Exception):
                record_sync_log(
                    db,
                    status="failed",
                    source="background_sync",
                    message=f"Background stock sync failed: {exc}",
                )
                db.commit()
        finally:
            db.close()
        await asyncio.sleep(interval)


def ensure_runtime_schema() -> None:
    with engine.begin() as conn:
        conn.execute(text("ALTER TABLE users ADD COLUMN IF NOT EXISTS is_superuser BOOLEAN NOT NULL DEFAULT false"))
        conn.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS market_status (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    status VARCHAR(128) NOT NULL,
                    source VARCHAR(64) NOT NULL DEFAULT 'ngx_doclib',
                    message TEXT,
                    raw_payload TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                )
                """
            )
        )
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_market_status_status ON market_status(status)"))
        conn.execute(
            text(
                """
                UPDATE users
                SET is_superuser = true
                WHERE id = (SELECT id FROM users ORDER BY id LIMIT 1)
                  AND NOT EXISTS (SELECT 1 FROM users WHERE is_superuser = true)
                """
            )
        )


@app.on_event("startup")
async def startup() -> None:
    global stock_sync_task
    Base.metadata.create_all(bind=engine)
    ensure_runtime_schema()
    if settings.enable_background_stock_sync:
        stock_sync_task = asyncio.create_task(background_stock_sync_loop())


@app.on_event("shutdown")
async def shutdown() -> None:
    if stock_sync_task is None:
        return
    stock_sync_task.cancel()
    with suppress(asyncio.CancelledError):
        await stock_sync_task


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/auth/register", response_model=UserOut, status_code=status.HTTP_201_CREATED)
def register(payload: RegisterRequest, db: Session = Depends(get_db)) -> User:
    existing = db.scalar(select(User).where(User.email == payload.email.lower()))
    if existing:
        raise HTTPException(status_code=409, detail="Email is already registered")
    user_count = db.scalar(select(func.count()).select_from(User)) or 0
    email = payload.email.lower()
    user = User(
        email=email,
        full_name=payload.full_name,
        password_hash=hash_password(payload.password),
        is_superuser=user_count == 0 or email in settings.admin_email_list,
    )
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


@app.post("/auth/login", response_model=TokenResponse)
def login(payload: LoginRequest, db: Session = Depends(get_db)) -> TokenResponse:
    user = db.scalar(select(User).where(User.email == payload.email.lower()))
    if user is None or not verify_password(payload.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Invalid email or password")
    return TokenResponse(access_token=create_access_token(user.id))


@app.get("/me", response_model=UserOut)
def me(user: User = Depends(get_current_user)) -> User:
    return user


@app.get("/market/status", response_model=MarketStatusOut)
def get_market_status(db: Session = Depends(get_db), _: User = Depends(get_current_user)) -> dict:
    return get_cached_market_status(db)


@app.get("/stocks", response_model=list[StockOut])
def list_stocks(
    search: str | None = None,
    db: Session = Depends(get_db),
    _: User = Depends(get_current_user),
) -> list[Stock]:
    query = select(Stock).order_by(Stock.symbol)
    if search:
        term = f"%{search.strip()}%"
        query = query.where((Stock.symbol.ilike(term)) | (Stock.name.ilike(term)))
    return list(db.scalars(query).all())


@app.get("/stocks/{symbol}", response_model=StockOut)
def get_stock(symbol: str, db: Session = Depends(get_db), _: User = Depends(get_current_user)) -> Stock:
    stock = db.get(Stock, symbol.strip().upper())
    if stock is None:
        raise HTTPException(status_code=404, detail="Stock not found")
    return stock


@app.get("/stocks/{symbol}/history", response_model=list[StockPriceOut])
def get_stock_history(
    symbol: str,
    months: int = Query(default=12, ge=1, le=120),
    db: Session = Depends(get_db),
    _: User = Depends(get_current_user),
):
    stock = db.get(Stock, symbol.strip().upper())
    if stock is None:
        raise HTTPException(status_code=404, detail="Stock not found")

    since = date.today() - relativedelta(months=months)
    rows = stock_history_query(db, symbol, since)
    if stock.ngx_id and (not rows or any(row.open_price is None for row in rows)):
        upsert_stock_history(db, stock.symbol, stock.ngx_id)
        db.commit()
        rows = stock_history_query(db, symbol, since)
    return rows


@app.post("/admin/sync/stocks", response_model=SyncResult)
def run_stock_sync(
    include_history: bool = False,
    db: Session = Depends(get_db),
    _: User = Depends(get_current_superuser),
) -> SyncResult:
    source, stock_count, history_count, sync_state, message = sync_stocks(db, include_history=include_history)
    return SyncResult(
        source=source,
        stocks_upserted=stock_count,
        history_rows_upserted=history_count,
        status=sync_state,
        message=message,
    )


@app.get("/admin/sync/status", response_model=SyncStatusOut)
def get_sync_status(db: Session = Depends(get_db), _: User = Depends(get_current_superuser)) -> dict:
    return sync_status(db)


@app.get("/admin/sync/logs", response_model=list[SyncLogOut])
def get_sync_logs(
    limit: int = Query(default=50, ge=1, le=200),
    db: Session = Depends(get_db),
    _: User = Depends(get_current_superuser),
):
    return sync_logs_query(db, limit)


@app.get("/portfolio/holdings", response_model=list[HoldingOut])
def list_holdings(db: Session = Depends(get_db), user: User = Depends(get_current_user)) -> list[dict]:
    holdings = db.scalars(
        select(PortfolioHolding)
        .options(selectinload(PortfolioHolding.stock))
        .where(PortfolioHolding.user_id == user.id)
        .order_by(PortfolioHolding.stock_symbol)
    ).all()
    return [holding_to_dict(holding) for holding in holdings]


@app.post("/portfolio/holdings", response_model=HoldingOut)
def save_holding(
    payload: HoldingUpsert,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user),
) -> dict:
    holding = upsert_holding(db, user, payload)
    return holding_to_dict(holding)


@app.delete("/portfolio/holdings/{symbol}", status_code=status.HTTP_204_NO_CONTENT)
def remove_holding(symbol: str, db: Session = Depends(get_db), user: User = Depends(get_current_user)) -> None:
    deleted = delete_holding(db, user, symbol)
    if not deleted:
        raise HTTPException(status_code=404, detail="Holding not found")
